- class: BottomLineMasking
  param_range:
    - n_repetitions: 1
    - n_repetitions: 2
    - n_repetitions: 5

- class: TopLineMasking
  param_range:
    - n_repetitions: 1
    - n_repetitions: 2
    - n_repetitions: 3

- class: LowNotesMasking
  param_range:
    - mask_percentage: 5
    - mask_percentage: 10
    - mask_percentage: 15
    - mask_percentage: 20
    - mask_percentage: 25
    - mask_percentage: 30
    - mask_percentage: 35
    - mask_percentage: 40
    - mask_percentage: 45
    - mask_percentage: 50
    - mask_percentage: 55
    - mask_percentage: 60
    - mask_percentage: 65
    - mask_percentage: 70
    - mask_percentage: 75
    - mask_percentage: 80
    - mask_percentage: 85
    - mask_percentage: 90
    - mask_percentage: 95
    - mask_percentage: 100

- class: HighNotesMasking
  param_range:
    - mask_percentage: 5
    - mask_percentage: 10
    - mask_percentage: 15
    - mask_percentage: 20
    - mask_percentage: 25
    - mask_percentage: 30
    - mask_percentage: 35
    - mask_percentage: 40
    - mask_percentage: 45
    - mask_percentage: 50
    - mask_percentage: 55
    - mask_percentage: 60
    - mask_percentage: 65
    - mask_percentage: 70
    - mask_percentage: 75
    - mask_percentage: 80
    - mask_percentage: 85
    - mask_percentage: 90
    - mask_percentage: 95
    - mask_percentage: 100

- class: ShortNotesMasking
  param_range:
    - mask_percentage: 5
    - mask_percentage: 10
    - mask_percentage: 15
    - mask_percentage: 20
    - mask_percentage: 25
    - mask_percentage: 30
    - mask_percentage: 35
    - mask_percentage: 40
    - mask_percentage: 45
    - mask_percentage: 50
    - mask_percentage: 55
    - mask_percentage: 60
    - mask_percentage: 65
    - mask_percentage: 70
    - mask_percentage: 75
    - mask_percentage: 80
    - mask_percentage: 85
    - mask_percentage: 90
    - mask_percentage: 95
    - mask_percentage: 100

- class: LongNotesMasking
  param_range:
    - mask_percentage: 5
    - mask_percentage: 10
    - mask_percentage: 15
    - mask_percentage: 20
    - mask_percentage: 25
    - mask_percentage: 30
    - mask_percentage: 35
    - mask_percentage: 40
    - mask_percentage: 45
    - mask_percentage: 50
    - mask_percentage: 55
    - mask_percentage: 60
    - mask_percentage: 65
    - mask_percentage: 70
    - mask_percentage: 75
    - mask_percentage: 80
    - mask_percentage: 85
    - mask_percentage: 90
    - mask_percentage: 95
    - mask_percentage: 100

- class: RandomMasking
  param_range:
    - mask_percentage: 5
    - mask_percentage: 10
    - mask_percentage: 15
    - mask_percentage: 20
    - mask_percentage: 25
    - mask_percentage: 30
    - mask_percentage: 35
    - mask_percentage: 40
    - mask_percentage: 45
    - mask_percentage: 50
    - mask_percentage: 55
    - mask_percentage: 60
    - mask_percentage: 65
    - mask_percentage: 70
    - mask_percentage: 75
    - mask_percentage: 80
    - mask_percentage: 85
    - mask_percentage: 90
    - mask_percentage: 95
    - mask_percentage: 100

- class: LinearRandomMasking
  param_range:
    - mask_percentage: 5
    - mask_percentage: 10
    - mask_percentage: 15
    - mask_percentage: 20
    - mask_percentage: 25
    - mask_percentage: 30
    - mask_percentage: 35
    - mask_percentage: 40
    - mask_percentage: 45
    - mask_percentage: 50
    - mask_percentage: 55
    - mask_percentage: 60
    - mask_percentage: 65
    - mask_percentage: 70
    - mask_percentage: 75
    - mask_percentage: 80
    - mask_percentage: 85
    - mask_percentage: 90
    - mask_percentage: 95
    - mask_percentage: 100

- class: BandRandomMasking
  param_range:
    - mask_percentage: 5
    - mask_percentage: 10
    - mask_percentage: 15
    - mask_percentage: 20
    - mask_percentage: 25
    - mask_percentage: 30
    - mask_percentage: 35
    - mask_percentage: 40
    - mask_percentage: 45
    - mask_percentage: 50
    - mask_percentage: 55
    - mask_percentage: 60
    - mask_percentage: 65
    - mask_percentage: 70
    - mask_percentage: 75
    - mask_percentage: 80
    - mask_percentage: 85
    - mask_percentage: 90
    - mask_percentage: 95
    - mask_percentage: 100
